### PR TITLE
Allow sort of search results by container (#396)

### PR DESCRIPTION
**Pull request by labkey-adam**

### CODE REVIEW

**Comment by labkey-adam** [comment]
BVTs look fine. I just kicked off a couple Search suite runs.

**Comment by labkey-adam** [comment]
@bbimber The four main search tests failed on both runs:

https://teamcity.labkey.org/viewLog.html?buildId=810076&buildTypeId=bt8
https://teamcity.labkey.org/viewLog.html?buildId=810074&buildTypeId=bt7

In all but one case, the "Sample" search query in the advanced UI test contained 6 results, but the tests expect 5. In the one remaining case, the test fails before getting into the new advanced UI method; looks like 5 results were returned, but this result seems to be missing: "sample.txt" attached to page "Roquefort".

I've merged from develop and queued up another set of Search suite runs. Not expecting the tests will pass, but maybe they'll fail more consistently.

**Comment by bbimber** [comment]
@labkey-adam ok.  the search tests were flaky when i tried them locally.  is there something related to when the crawler finishes, perhaps?

**Comment by labkey-adam** [comment]
Yes, they are not super reliable. Still seems a good bet to expect 6 results on the project search... that's a consistent result. I'll change that and re-run.

**Comment by labkey-adam** [comment]
Looks like the container SortedDocValuesField bit didn't get included in the patch that was merged to this branch. (It's in the patches in the ticket, but not here.) I can add... is there anything needed beyond the SortedDocValuesField line?

**Comment by bbimber** [comment]
Sorry, no i dont believe so.

**Comment by bbimber** [comment]
wow I totally forgot about this one

**Comment by labkey-adam** [comment]
Yeah, it's been on the back burner. I haven't been able to get your new tests to run consistently on TeamCity. Going to ask for Trey for some help. I just implemented "near real-time indexing" which may help provide more consistency. But either way, I'd like to get this in...

**Comment by labkey-adam** [comment]
@labkey-tchad when you get a chance, can you review the test results here and approve (or not)? Ben added a new test case for sorting by folder path and it looks like all is good on PostgreSQL now. Thanks.

**Review by labkey-tchad — APPROVED** [review]
The SQL Server failure looks like the normal flakiness when searching after a list update

**Comment by labkey-adam** [comment]
At long last...

**Comment by bbimber** [comment]
woo hoo!

**Comment by bbimber** [comment]
now did i enable natural sort?

**Pull request merged**
