### PR TITLE
39535: Custom banner needs to 'flex' to the container width

### PR DESCRIPTION
**Pull request by labkey-klum**

### CODE REVIEW

**Comment by labkey-klum** [comment]
Cory, let me know if you want to discuss this change. I originally added the content-banner style to the row div that encloses the custom banner. In retrospect this was wrong since we want that row to be the full width of the page. I was mimicking the row-content style but I now understand that the flex display style was present so that we could use flex-grow for the left and right webparts.

**Review by cnathe — APPROVED** [review]
This change looks good. Your description makes sense. Looking at the 19.3 code, it looks like the only place this class is used is in body.jsp. Any reason not to remove the class from the div there as well?

**Comment by labkey-klum** [comment]
@cnathe , I was trying to decide whether it made sense to leave the content-banner class in the div as a marker class if that could be useful but I it would also make sense to remove it entirely. Do you have any thoughts about this, do we have any precedence for doing these types of things?

**Comment by cnathe** [comment]
> @cnathe , I was trying to decide whether it made sense to leave the content-banner class in the div as a marker class if that could be useful but I it would also make sense to remove it entirely. Do you have any thoughts about this, do we have any precedence for doing these types of things?

@labkey-klum Good point, I think leaving it in as a marker makes sense. Might be useful for automated tests or for client's code to latch on to.

**Pull request merged**
