### PR TITLE
Make tests work with CAS-only server

### PR DESCRIPTION
**Pull request by labkey-tchad**
#### Rationale
Our automated tests should be more flexible about the configuration of the server they wish to test. Many tests currently require database authentication against a server running locally with a full dev enlistment and a test user with site admin permission. Most if not all of these restrictions are not actually necessary for most of our automated tests.
When using the remote API, tests should use the browser's existing session when possible instead of requiring database authentication.

#### Related Pull Requests
* https://github.com/LabKey/testAutomation/pull/369

#### Changes
* (test) Avoid using API helpers during impersonation
* (test) Refactor `createDefaultConnection(true)` to `createDefaultConnection()`
* (product) Add `@AllowedOutsideImpersonationProject` to allow `StopImpersonationAction` to work more universally.

### CODE REVIEW

**Review by labkey-danield — COMMENTED** [review]
I'm ok with the test code but will defer signing off until Adam (or another dev) reviews the product code.

**Review by labkey-adam — APPROVED** [review]
Product changes look good.

Just making sure: you want to merge this to develop, not 20.7?

Where is no-param createDefaultConnection() defined?

**Comment by labkey-tchad** [comment]
> Just making sure: you want to merge this to develop, not 20.7?

Correct. This change is too potentially disruptive and I've already merged in some develop changes anyway.
 
> Where is no-param createDefaultConnection() defined?

It's added in the [testAutomation PR](https://github.com/LabKey/testAutomation/pull/369). It's equivalent to `createDefaultConnection(true)`

**Comment by labkey-adam** [comment]
Fair enough... I'm good with this

**Pull request merged**
