### PR TITLE
use verbose fieldnames to clarify usages

### PR DESCRIPTION
**Pull request by labkey-matthewb**
#### Rationale
fix for unique column names

#### Related Pull Requests
* 

#### Changes
*

### CODE REVIEW

**Comment by labkey-adam** [comment]
@labkey-matthewb do you want to close this in favor of the 23.3 PR?

**Comment by labkey-matthewb** [comment]
> @labkey-matthewb do you want to close this in favor of the 23.3 PR?

I'm going to as the AM

**Comment by labkey-matthewb** [comment]
If

> @labkey-matthewb do you want to close this in favor of the 23.3 PR?

I would probably leave this open until the 23.3 PR can be merged forward, and then do this PR to pick up the Junit test.

**Comment by labkey-adam** [comment]
> If
> 
> > @labkey-matthewb do you want to close this in favor of the 23.3 PR?
> 
> I would probably leave this open until the 23.3 PR can be merged forward, and then do this PR to pick up the Junit test.

Gotcha, makes sense. I'll hold off on approving until the merges to develop and then from develop to this FB happen.

**Review by labkey-adam — APPROVED** [review]

**Pull request merged**
