### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by labkey-matthewb**
#### Rationale
missing ```nonce=```

#### Related Pull Requests
* 

#### Changes
*

### CODE REVIEW

**Review by labkey-adam — APPROVED** [review]
So this wasn't correct? My FB passed the BVT and I thought BVTs ran with CSP in place.

**Comment by labkey-matthewb** [comment]
> So this wasn't correct? My FB passed the BVT and I thought BVTs ran with CSP in place.

Maybe Trey switched from "enforce" to "report" so all the tests run with one configuration?

**Comment by labkey-tchad** [comment]
BVTs are set to enforce. Enforcing just makes the javascript not execute; it would only cause a test failure if the javascript not executing would interfere with the tests. In this case, the difference is purely cosmetic as we don't yet test the strength meter.

**Comment by labkey-matthewb** [comment]
> BVTs are set to enforce. Enforcing just makes the javascript not execute; it would only cause a test failure if the javascript not executing would interfere with the tests. In this case, the difference is purely cosmetic as we don't yet test the strength meter.

Right, I didn't actually look at what was in the <script> block.

**Comment by labkey-adam** [comment]
> > BVTs are set to enforce. Enforcing just makes the javascript not execute; it would only cause a test failure if the javascript not executing would interfere with the tests. In this case, the difference is purely cosmetic as we don't yet test the strength meter.
> 
> Right, I didn't actually look at what was in the <script> block.

You should... there's excellent work in there! 😄 

Thanks for the clarification, Trey... that makes sense. Time for me to turn my local CSP back on.

**Pull request merged**
