### PR TITLE
Issue 42295: ClassCastException in MetricJSONDisplayColumn

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Rationale
Our new approach of using a JSONB column for these metrics means we don't need to use a tricky DisplayColumn to pull out specific metrics. Thus, we can remove this now unused code.

I considered moving it out of Mothership into Core or API because it's potentially useful in other scenarios. But without a concrete use case, I figured it was best to shed the third-party dependency and reduce our code footprint.

#### Changes
* Remove MetricJSONDisplayColumn, its factory, and the small library it used for pull the JSON data

### CODE REVIEW

**Comment by labkey-adam** [comment]
Looks like some jayway references in MothershipController

**Review by labkey-ankurj — APPROVED** [review]

**Review by labkey-adam — CHANGES_REQUESTED** [review]
Probably should build

**Comment by labkey-jeckels** [comment]
Picky, picky

**Review by labkey-adam — APPROVED** [review]
Fabulous

**Pull request merged**
