### PR TITLE
Move unused pivot.jsp

### PR DESCRIPTION
**Pull request by labkey-matthewb**
#### Rationale
Moving unused pivot.jsp to devtools module (because it is a useful example).

#### Related Pull Requests
- 

#### Changes
-

### CODE REVIEW

**Review by labkey-adam — CHANGES_REQUESTED** [review]
I know this is a (broken) example, but could you migrate the three inline event handlers and HTML encode the content? These are the last inline handlers in our repositories. And would be good to follow best practices in sample code.

**Comment by labkey-matthewb** [comment]
> I know this is a (broken) example, but could you migrate the three inline event handlers and HTML encode the content? These are the last inline handlers in our repositories. And would be good to follow best practices in sample code.

Hmm, I must have overwritten my changes when I refactored/moved the file...

**Comment by labkey-matthewb** [comment]
> > I know this is a (broken) example, but could you migrate the three inline event handlers and HTML encode the content? These are the last inline handlers in our repositories. And would be good to follow best practices in sample code.
> 
> Hmm, I must have overwritten my changes when I refactored/moved the file...

Found the changes hanging out over in the specimens module

**Review by labkey-adam — APPROVED** [review]
Code assumes that `member.uniqueName` and `member.name` are HTML-safe without any encoding, but that seems like a reasonable assumption.

**Pull request merged**
