### PR TITLE
Use correct helper and page for dataset metadata

### PR DESCRIPTION
**Pull request by labkey-tchad**

### CODE REVIEW

**Review by cnathe — APPROVED** [review]

**Comment by labkey-tchad** [comment]
Verifying: https://teamcity.labkey.org/viewLog.html?buildId=956645&buildTypeId=LabKey_204Release_Community_BvtSqlserver

The test is still failing but it seems to be because of a change in product behavior. The "exclude from date shifting" flag is getting set in the dataset's metadata but it isn't respected when we publish. When I go to the domain designer for the dataset, it doesn't reflect the changes made through the metadata editor.
I'm not too clear on what the relationship is between the domain and metadata for a dataset but it seems to not be behaving as expected.

**Comment by cnathe** [comment]
> Verifying: https://teamcity.labkey.org/viewLog.html?buildId=956645&buildTypeId=LabKey_204Release_Community_BvtSqlserver
> 
> The test is still failing but it seems to be because of a change in product behavior. The "exclude from date shifting" flag is getting set in the dataset's metadata but it isn't respected when we publish. When I go to the domain designer for the dataset, it doesn't reflect the changes made through the metadata editor.
> I'm not too clear on what the relationship is between the domain and metadata for a dataset but it seems to not be behaving as expected.

When I pull this up locally in the UI, I see the following:
1. the dataset domain designer (GWT version) says that the "exclude from shifting" option for my date field is unchecked. that looks right
2. when I go to the query metadata editor for that same date field, that "exclude from shifting" checkbox in the advanced settings dialog is checked. that is not what I expected.
3. if I uncheck it in the query metadata editor and save and then click "Edit Source", I get         <excludeFromShifting>true</excludeFromShifting>. this is not what I expected
4. also, I set some other things in the query metadata editor for that field (i.e. description, label, url, import aliases) and saved. Those all show in the edit source page as expected, but when I go back to the query metadata editor UI, not all of them re-show as expected in the UI.
We should get an issue opened on these items. @labkey-ankurj can you take a look into this behavior?

**Comment by cnathe** [comment]
I created an issue for this here: https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=40106

**Comment by labkey-tchad** [comment]
Now passing: https://teamcity.labkey.org/viewLog.html?buildId=956882&buildTypeId=LabKey_204Release_Community_BvtSqlserver

**Review by labkey-ankurj — APPROVED** [review]

**Pull request merged**
