### PR TITLE
Include jdbcType in the column JSON, in addition to SqlType

### PR DESCRIPTION
**Pull request by bbimber**
Include jdbcType in the column JSON, in addition to SqlType. When the type is timestamp, access to the raw jdbctype (which might be either binary or datetime) is necessary

### CODE REVIEW

**Comment by bbimber** [comment]
@labkey-martyp or @labkey-jeckels: would you mind mirroring this into the LK org so TeamCity will pick this up? I'll explain the purpose in the other PR: https://github.com/LabKey/dataintegration/pull/202

**Comment by labkey-martyp** [comment]
@bbimber Ok this is merged into the LabKey 23.3_fb_remoteDelete

**Comment by labkey-jeckels** [comment]
@labkey-tchad TeamCity build status isn't getting updated in this PR? Is there a mismatch somewhere?

https://teamcity.labkey.org/buildConfiguration/LabKey_233Release_Premium_VerifyJavaBuild?branch=remoteDelete&mode=builds

**Comment by bbimber** [comment]
@labkey-jeckels : isnt this b/c i cant make branches on the labkey org? would you be able to mirror my branch here? or maybe consider giving me permission to create feature branches so I dont need to keep bugging you?

**Comment by labkey-jeckels** [comment]
Marty's already mirrored the branch into the LK repo and two builds have already completed on TeamCity. Usually that's enough to have status show in the PR.

https://github.com/LabKey/platform/tree/23.3_fb_remoteDelete

**Comment by labkey-tchad** [comment]
> @bbimber Ok this is merged into the LabKey 23.3_fb_remoteDelete

Merging isn't helpful. The branch on the labkey side has to be on the exact same commit for status to show up here.

**Comment by labkey-tchad** [comment]
Needed a merge from 23.3-SNAPSHOT. I did the merge in the LK branch. If you fast-forward this branch you can pick up the status that TeamCity will report (GitHub status is attached to particular commits, not to branches or PRs).
```
git fetch --all
git merge --ff-only 9fffd07643d1d9e663e3ecd6d5951ea9d2a1f193
```

**Comment by bbimber** [comment]
@labkey-martyp: see comment here: https://github.com/LabKey/dataintegration/pull/202. Also, I unfortunately need you to merge my last change into the LK side of the fork to get TeamCity to pick up on it.

**Comment by labkey-martyp** [comment]
Trying to get TC to pick this up is a PIA so I just opened another PR on the LK side with your changes. Running tests on that now.

**Comment by bbimber** [comment]
@labkey-martyp, thanks! i should be getting write access here, which would make this kind of thing much, much more streamlined.

**Comment by bbimber** [comment]
Now that we have a proper LK branch, I'm closing this in favor of that one to keep it simpler.

**Pull request closed without merging**
