### PR TITLE
Issue 39869: Use Source ID instead of Name for Sources in Sample Manager

### PR DESCRIPTION
**Pull request by labkey-susanh**

### CODE REVIEW

**Review by XingY — CHANGES_REQUESTED** [review]
We should add "SourceID" to dataclass reserved fields.

**Comment by labkey-susanh** [comment]
We will do that checking for SourceID within the application code.  Since @cnathe is doing a refactor of the Designers in his [fb_smSampleTypeDesignerPolish](https://github.com/LabKey/labkey-ui-components/pull/195) branch of ui-components, I'm going to defer making changes for this check until that branch has been merged through.

**Comment by cnathe** [comment]
> We will do that checking for SourceID within the application code. Since @cnathe is doing a refactor of the Designers in his [fb_smSampleTypeDesignerPolish](https://github.com/LabKey/labkey-ui-components/pull/195) branch of ui-components, I'm going to defer making changes for this check until that branch has been merged through.

I agree with waiting until my domain designer refactors are merged in before adding this. I can help add it if you'd like.

**Comment by labkey-susanh** [comment]
> We should add "SourceID" to dataclass reserved fields.

I've opened a separate [issue](https://www.labkey.org/home/Developer/issues/issues-details.view?issueId=40088) for this to be handled after we get some of the current branches merged.

**Review by cnathe — APPROVED** [review]

**Review by XingY — APPROVED** [review]

**Pull request merged**
