### PR TITLE
Migrate to new JSONObject/JSONArray

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Comment by bbimber** [comment]
@labkey-adam, @labkey-jeckels or others: i cant make branches on the LabKey org, which is needed for TeamCity to pick this up. Would someone be able to do this?

**Comment by bbimber** [comment]
@labkey-adam, @labkey-jeckels or others: i cant make branches on the LabKey org, which is needed for TeamCity to pick this up. Would someone be able to do this?

**Comment by labkey-adam** [comment]
@bbimber yes, we'll take care of this shortly

**Comment by labkey-adam** [comment]
@bbimber I believe I've created TeamCity-accessible feature branches for all your PRs (platform, onprc, discvr, labdevkit, bimberlabkey). Tests started running (and failed) before all FBs were created. I'll re-queue the failed tests.

**Comment by bbimber** [comment]
@labkey-adam, thanks. for my knowledge, is there a more correct way to kick off multiple coordinated PRs that depend on one another? 

If anyone knows gradle, I think this issue might cause another build failure. I tried to migrate LDK/laboratory code from platform, and gradle isnt recognizing the new dependencies: https://www.labkey.org/ONPRC/Support%20Tickets/issues-details.view?issueId=47287

**Comment by labkey-adam** [comment]
> @labkey-adam, thanks. for my knowledge, is there a more correct way to kick off multiple coordinated PRs that depend on one another?
> 
> If anyone knows gradle, I think this issue might cause another build failure. I tried to migrate LDK/laboratory code from platform, and gradle isnt recognizing the new dependencies: https://www.labkey.org/ONPRC/Support%20Tickets/issues-details.view?issueId=47287

@bbimber I'm not aware of a better workflow. Normally, it would go faster, but I haven't ever created FBs against fork PRs I was slow to get them all created.

I'll look at the build failure, but we might need to bring in @labkey-susanh , who's mostly OOO today.

**Comment by labkey-adam** [comment]
> 
> I'll look at the build failure, but we might need to bring in @labkey-susanh , who's mostly OOO today.

@bbimber see my reply in the issue

**Review by labkey-adam — APPROVED** [review]

**Comment by bbimber** [comment]
@labkey-adam thanks - just a reminder i dont have write permission to actually merge this.

**Comment by labkey-adam** [comment]
> @labkey-adam thanks - just a reminder i dont have write permission to actually merge this.

Yep, I plan to initiate all the merges myself (after one more PR review and I figure out how to get this PR to see the successful premium build)... unless you're dying to do some of the merges.

**Pull request merged**
