### PR TITLE
Encode display name in WebDav response

### PR DESCRIPTION
**Pull request by labkey-tchad**

### CODE REVIEW

**Comment by labkey-tchad** [comment]
Fix for WebDavTest failures. In our webdav listing response, we were encoding 'createdBy':
`<createdby>tchad--&gt;&quot;&gt;&#039;&gt;&#039;&quot;&lt;img src=&quot;xss&quot; onerror=&quot;alert(&#039;8(&#039;)&quot;&gt;</createdby>`
but not 'modifiedBy':
`<modifiedby>tchad-->">'>'"</modifiedby>`

@labkey-jeckels: May be worth backporting to panoramaweb18.3 or at least being aware of if they have any WebDav problems.

**Comment by labkey-jeckels** [comment]
Let's refactor so that all values that get passed to writeProperty() gets encoded automatically. Otherwise, all callers have to remember to do this in the future.

**Comment by labkey-adam** [comment]
As an aside, generalizing and expanding the use of _HtmlString (renaming it SafeHtml or something) would give us the option of eliminating String values like this... and the inherent risk of not encoding and double encoding.

**Comment by labkey-tchad** [comment]
Yup. I missed a step in my refactor plan. re-refactor incoming

**Pull request merged**
