### PR TITLE
getRemoteAddr() helper that uses X-Forwarded-For header

### PR DESCRIPTION
**Pull request by labkey-matthewb**
#### Rationale
Load balancers

#### Related Pull Requests
- 

#### Changes
-

### CODE REVIEW

**Review by labkey-jeckels — APPROVED** [review]
Looks good. Note that it swaps `getRemoteAddr()` where it previously used `getRemoteHost()`. Seems fine.

There are a handful of other places to call either method. Most also check for the header. Probably we should consolidate and even add an IntelliJ warning to steer people to the utility code.

**Comment by labkey-matthewb** [comment]
> Looks good. Note that it swaps `getRemoteAddr()` where it previously used `getRemoteHost()`. Seems fine.
> 
> There are a handful of other places to call either method. Most also check for the header. Probably we should consolidate and even add an IntelliJ warning to steer people to the utility code.

I figured migrating other usages could  be done on develop.

**Comment by labkey-matthewb** [comment]
PopZ

**Comment by labkey-jeckels** [comment]
> > Looks good. Note that it swaps `getRemoteAddr()` where it previously used `getRemoteHost()`. Seems fine.
> > There are a handful of other places to call either method. Most also check for the header. Probably we should consolidate and even add an IntelliJ warning to steer people to the utility code.
> 
> I figured migrating other usages could be done on develop.

Yup. Sounds good!

**Pull request merged**
