### PR TITLE
Delete unused JSP and its commented reference

### PR DESCRIPTION
**Pull request by labkey-jeckels**
#### Rationale
This JSP has been orphaned for 17+ months. No need to keep it around and cluttering the report of unused JSPs

#### Changes
* Remove unused JSP and now no-op overridden method that once referenced it

### CODE REVIEW

**Comment by labkey-tchad** [comment]
@labkey-matthewb Near the end of the PR when that test was introduced (#825), there was a commit disabling it "temporarily": https://github.com/LabKey/platform/pull/825/commits/5f988307ebd20c649ea9c5a5e1c4e50a15ec6c82

**Review by labkey-matthewb — COMMENTED** [review]
Not sure why this is was commented out.  Is SimpleModule.canBeEnabled() tested elsewhere?

**Comment by labkey-tchad** [comment]
It doesn't look like it is being tested anywhere else.

**Comment by labkey-tchad** [comment]
Let's see what happens if we enable it: #2531

**Comment by labkey-tchad** [comment]
The test found an issue, so we should probably fix that and enable the test. Should probably fix the bug and close this PR.

**Comment by labkey-tchad** [comment]
Test is needed. Updating and enabling in #2531

**Pull request closed without merging**
