### PR TITLE
Issue 45408: Option to export the results of Validate Queries

### PR DESCRIPTION
**Pull request by XingY**
#### Related Pull Requests
* 

#### Changes
* Added "Export" button to export validation result to excel

### CODE REVIEW

**Comment by labkey-tchad** [comment]
This is currently breaking the build. Can't use ES6 `const` keyword in plain JavaScript files.
This is caused by YUICompressor in production builds.

**Comment by XingY** [comment]
> This is currently breaking the build. Can't use ES6 `const` keyword in plain JavaScript files. This is caused by YUICompressor in production builds.

Thanks. Changed const to var

**Comment by labkey-tchad** [comment]
The build is still broken. Not sure what else in this change isn't ES5 compatible

**Comment by XingY** [comment]
> The build is still broken. Not sure what else in this change isn't ES5 compatible

Could be the array spread operation

**Review by labkey-matthewb — APPROVED** [review]

**Pull request merged**
