### PR TITLE
Issue 37866: NPE in ExperimentController$ShowFileAction.getDataView()

### PR DESCRIPTION
**Pull request by labkey-jeckels**
Defer to FileContentService to figure out correct file root for a container, instead of handling various options in PipelineServiceImpl

Make FileContentService.getContainersForFilePath() NotNull

### CODE REVIEW

**Comment by bbimber** [comment]
@labkey-jeckels : I noticed a few other things: based on our forum thread, I tried to set a folder-level pipeline override to match the file root override.  There a couple issues:

1) In pipeline module's setup.jsp, the idea should be that if there is no pipeline override, we use the default file root of this folder.  what's happening is that it instead uses the default file root based on the site root.  The attached patch has some comments (i might have been able to comment here but dont know how to add other files).

2) PipelineServiceImpl.getDefaultPipelineRoot() line 213 calls svc.isUseDefaultRoot(container.getProject()).  I dont believe it should call getProject(), should it?  This is related to #1.


[PipelineRoot.patch.txt](https://github.com/LabKey/platform/files/3347237/PipelineRoot.patch.txt)

**Comment by bbimber** [comment]
@labkey-jeckels I have been running this on our 19.1 branch and it seems OK.  Also, this change is going to need updates in PipelineServiceImpl$TestCase.  You'll see that when a folder has a custom file root and no otherwise overriden pipeline root, isDefault() now returns true.  This is b/c the pipeline root matches the active file root.  previously it tested whether the pipeline root matched the expected root based on the site file root.  I'm not sure whether this is advisable to simply update the expectations of this method, or update that method to check against site file root default.

**Comment by labkey-jeckels** [comment]
@bbimber PipelineServiceImpl$TestCase is passing for me locally. Are you seeing a failure, or suggesting that we should be adding new coverage?

As for the comments in the patch you attached, in the PR already removes the incorrect call to use the project instead of the current container in PipelineServiceImpl, around line 210. I think that also takes care of the other concern.

Am I missing anything? If not, I can go ahead and merge this for 19.2.

**Comment by bbimber** [comment]
@labkey-jeckels Yes, I realized that you already fixed the getProject() call after I wrote my comment.  I do not have concerns here.

I see a variety of failures in PipelineServiceImpl$TestCase on 19.2 with this patch.  At least some of them appear to be windows-related, and maybe this is the cause of everything I'm seeing.  Most failures are some variation on an assert() trying to compare two path strings, and one is a linux-style path string and the other is the window-style path string.  So far as I can tell, the paths are actually the same - just different formatting.  I find it odd that it doesnt fail on trunk, since team city uses some windows agents.  It's possible my local DB has a value for file/pipeline root set in a manner that triggers this.  Anyway, if it passes for you I dont have any new concerns.

**Comment by labkey-jeckels** [comment]
Kicked off DRTs on TeamCity to see if this will be happy there too:

https://teamcity.labkey.org/viewQueued.html?itemId=781704

https://teamcity.labkey.org/viewQueued.html?itemId=781702

**Comment by labkey-jeckels** [comment]
Updated PR is at https://github.com/LabKey/platform/pull/260

**Pull request closed without merging**
