### PR TITLE
Issue #40862

### PR DESCRIPTION
**Pull request by labkey-adam**
#### Rationale
[Issue 40862: Migrate wiki ad hoc \<select> elements to SelectBuilders](https://www.labkey.org/home/Developer/issues/Secure/issues-details.view?issueId=40862)

#### Changes
* Convert some ad hoc \<select> elements to SelectBuilders
* Override default `cellTpl` for `Ext4.tree.Column`

### CODE REVIEW

**Comment by labkey-adam** [comment]
Build and BVTs are green. Now running the Wiki suite (disguised as BVT Postgres).

**Review by labkey-jeckels — APPROVED** [review]

**Comment by labkey-nicka** [comment]
In addition to the ExtJS fix I've pushed a fix for the `WikiLongTest` failure.

**Comment by labkey-jeckels** [comment]
Will this potentially double-encode in places like the schema browser, where I think/hope we've already done encoding?

**Comment by labkey-nicka** [comment]
> Will this potentially double-encode in places like the schema browser, where I think/hope we've already done encoding?

Likely. It looks like we ask the server to do the encoding in that case.

```js
LABKEY.ActionURL.buildURL('query', 'getSchemaQueryTree.api', null, {showHidden : this.showHidden, withHtmlEncoding:true})
```

**Pull request merged**
