### PR TITLE
Perf improvement for AtomicDatabaseInteger

### PR DESCRIPTION
**Pull request by labkey-matthewb**
#### Rationale
Perf  improvement for AtomicDatabaseInteger.  Table.update() is expensive when you don't need the generality.

### CODE REVIEW

**Review by labkey-adam — APPROVED** [review]

**Comment by labkey-adam** [comment]
Actually, just noticed that you can delete _user, since it's no longer used

**Comment by labkey-matthewb** [comment]
> Actually, just noticed that you can delete _user, since it's no longer used

OK, had to fix call in OConnorLabModules

**Comment by labkey-adam** [comment]
Is that the only code that uses these things?

**Comment by labkey-matthewb** [comment]
> Is that the only code that uses these things?

Looks like it.  Usages might have migrated to DbSequenceManager?

**Comment by labkey-adam** [comment]
Ah, right, very different things

**Pull request merged**
