### PR TITLE
Make `SimpleModule.canBeEnabled` work properly on Windows

### PR DESCRIPTION
**Pull request by labkey-tchad**
#### Rationale
This test was "temporarily" disabled shortly before getting merged to develop.

#### Related Pull Requests
* #825

#### Changes
* Enable `testSimpleModule`

### CODE REVIEW

**Comment by labkey-tchad** [comment]
@labkey-matthewb This test fails on Windows
```
java.lang.AssertionError: SimpleModule.canBeEnabled: folderPathPattern="regex:(/a/b)|(/a/b/.*)" Container=/a/b/c1 expected:<true> but was:<false>
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.failNotEquals(Assert.java:835)
  at org.junit.Assert.assertEquals(Assert.java:120)
  at org.labkey.jsp.compiled.org.labkey.api.module.testSimpleModule_jsp.assertCanBeEnabled(testSimpleModule_jsp.java:103)
  at org.labkey.jsp.compiled.org.labkey.api.module.testSimpleModule_jsp.testGlob(testSimpleModule_jsp.java:66)
```

**Comment by labkey-jeckels** [comment]
@labkey-matthewb this is presumably because Windows uses \ ? Do you want a bug on this?

**Comment by labkey-tchad** [comment]
@labkey-matthewb Changed `isEnabled` to use `FileSystem.getPathMatcher` only for glob patterns. It now uses the vanilla `java.util.regex.Matcher#matches` for regex patterns.

**Comment by labkey-matthewb** [comment]
> @labkey-matthewb Changed `isEnabled` to use `FileSystem.getPathMatcher` only for glob patterns. It now uses the vanilla `java.util.regex.Matcher#matches` for regex patterns.

Internally FileSystem.getPathMatcher() already just calls Pattern.compile() for regexp patterns.

**Comment by labkey-tchad** [comment]
> > @labkey-matthewb Changed `isEnabled` to use `FileSystem.getPathMatcher` only for glob patterns. It now uses the vanilla `java.util.regex.Matcher#matches` for regex patterns.
> 
> Internally FileSystem.getPathMatcher() already just calls Pattern.compile() for regexp patterns.

True, but we have to pass it an `nio.Path` which flips all of the container path's slashes on Windows. This change just matches the container path String directly.

**Review by labkey-jeckels — APPROVED** [review]

**Pull request merged**
