### PR TITLE
Compile with Java 16 source & target

### PR DESCRIPTION
**Pull request by labkey-adam**
#### Rationale
Allow Java 16 syntax

#### Related Pull Requests
* https://github.com/LabKey/server/pull/153

### CODE REVIEW

**Review by labkey-susanh — APPROVED** [review]

**Comment by labkey-susanh** [comment]
The change from 14 to 16 seems straightforward enough, but it looks like something else is required to make this go.

**Comment by labkey-adam** [comment]
@labkey-tchad @labkey-susanh Yes, TeamCity needs to be configured to compile with JDK 16 on develop

**Comment by labkey-tchad** [comment]
Updated TeamCity to use Java 16 and merged from develop to trigger tests to run

**Comment by labkey-tchad** [comment]
Build is failing with:
```
Execution failed for task ':server:embedded:bootJar'.
     > Error while evaluating property 'mainClassName' of task ':server:embedded:bootJar'
        > Unsupported class file major version 60
```
Other branches are not showing this error.

**Comment by labkey-jeckels** [comment]
That means that something older than Java 16 is trying to read a Java 16-compiled class. Class version 60 is what the Java 16 compiler target produces.

https://en.wikipedia.org/wiki/Java_class_file

**Comment by labkey-adam** [comment]
Which build/repo/branch shows the failure? TeamCity link?

**Comment by labkey-tchad** [comment]
The failure is from this branch. It was the first build on the agent, so there isn't anything lingering from a previous build.
https://teamcity.labkey.org/buildConfiguration/bt2/1621223

**Comment by labkey-adam** [comment]
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 60
       at org.springframework.asm.ClassReader.<init>(ClassReader.java:196)
       at org.springframework.asm.ClassReader.<init>(ClassReader.java:177)
       at org.springframework.asm.ClassReader.<init>(ClassReader.java:163)
       at org.springframework.asm.ClassReader.<init>(ClassReader.java:284)
       at org.springframework.boot.loader.tools.MainClassFinder.createClassDescriptor(MainClassFinder.java:25
       at org.springframework.boot.loader.tools.MainClassFinder.doWithMainClasses(MainClassFinder.java:136)
       at org.springframework.boot.loader.tools.MainClassFinder.findSingleMainClass(MainClassFinder.java:109)
       at org.springframework.boot.gradle.plugin.MainClassConvention.findMainClass(MainClassConvention.java:9
       at org.springframework.boot.gradle.plugin.MainClassConvention.resolveMainClass(MainClassConvention.jav
       at org.springframework.boot.gradle.plugin.MainClassConvention.call(MainClassConvention.java:60)
```
Looks like SpringBoot is attempting to read some class (via ASM) and failing. Our SpringBoot version is way out-of-date: 2.2.x was end-of-lifed in July. 2.5.x is the first SB version to claim Java 16 support. 2.6.1 is the latest.

**Comment by labkey-adam** [comment]
I think we'll need to upgrade SpringBoot before we can require JDK 16. But I'm not the CTO 😄

**Comment by labkey-jeckels** [comment]
@labkey-tchad test build is now failing. IAJC seems unhappy with the newer Java version.

**Comment by labkey-adam** [comment]
FYI: I've been testing a newer version of AspectJ (1.9.8.RC3) over here: https://github.com/LabKey/testAutomation/pull/880

However, it's hard to imagine how running with AspectJ 1.9.7 would cause these failures. I've built the tests with JDK 16 and 17 many times.

**Comment by labkey-adam** [comment]
`Syntax error, annotations are only available if source level is 1.5 or greater` (!!)

It looks like somebody is very confused about the source level

**Comment by labkey-adam** [comment]
Looks like we do need the AspectJ upgrade. I've created an `fb_java16` branch off my feature branch and kicked off a bunch of test suites.

**Comment by labkey-adam** [comment]
Okay, that looks much better. We do have a strange DRT failures: `ciTestsSqlserver2019` and `ciTestsPostgres13` (what are those?) both failing with "Could not find matching constructor for: java.io.File(String, File)". That's a private constructor. Anybody?

**Comment by labkey-adam** [comment]
https://teamcity.labkey.org/viewLog.html?buildId=1621836&buildTypeId=bt3

**Comment by labkey-jeckels** [comment]
@labkey-tchad @labkey-susanh this looks like a problem in how TeamCity and Gradle are interacting with each other. I found this in the test logs in TeamCity:

Caused by: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.io.File(String, File)
at TestDescriptorWrapper.attacheBigFailTestMessage(/opt/teamcity-agent/plugins/gradle-runner/scripts/init.gradle:759)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at TestDescriptorWrapper.result(/opt/teamcity-agent/plugins/gradle-runner/scripts/init.gradle:679)
at TestDescriptorWrapper$result$2.call(Unknown Source)

https://teamcity.labkey.org/buildConfiguration/bt3/1621836?showLog=1621836_5876_849.5853.5861&logFilter=debug

**Comment by labkey-tchad** [comment]
Looks like a bug in TeamCity's gradle plugin: https://github.com/JetBrains/teamcity-gradle/issues/6
I'll see what I can do about updating that plugin.

**Comment by labkey-adam** [comment]
@labkey-tchad any luck getting TeamCity's gradle plugin updated? Or let me know if I should merge these PRs before the update.

**Comment by labkey-tchad** [comment]
The fix is in the next version of TeamCity. We're scheduled to upgrade on the 12th.

**Pull request merged**
