### PR TITLE
Remove unused methods

### PR DESCRIPTION
**Pull request by bbimber**

### CODE REVIEW

**Comment by bbimber** [comment]
@labkey-adam @labkey-jeckels I'm not sure if this over-complicates, but since both platform and LabDevKitModules need paired changes I'm merging this into here.  The corresponding changes in LaboratoryModule are in the other PR.

**Comment by bbimber** [comment]
Also - do you know if it is now possible to refactor LaboratoryService out of platform and into LaboratoryModule's API directly?  I believe the reason it lives here (and it's been a while), is b/c other API modules reference it.  We still have a handful of classes that live in platform, rather than our repos.

**Review by labkey-jeckels — APPROVED** [review]

**Comment by labkey-jeckels** [comment]
@bbimber I don't think anything has changed in terms of the API-scoping rules, so I don't think it's yet possible to move these out of Platform.

**Comment by bbimber** [comment]
@labkey-jeckels OK.  Also, I dont appear to actually have merge permissions here?

**Comment by labkey-jeckels** [comment]
@bbimber Either @labkey-adam or I will merge this along with the other related PRs, including https://github.com/LabKey/LabDevKitModules/pull/27/files# once we've double-checked that TeamCity is happy

**Comment by labkey-adam** [comment]
@bbimber Now that this is merged, we'll need to wait for TeamCity verification before merging the next seven PRs. I should be able to later this afternoon.

**Pull request merged**
